/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.ProductManagement;

import TheBusiness.Business.Business;
import javax.swing.JPanel;

/**
 *
 * @author Sandeep Patil
 */
public class MarketingWorkspaceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MarketingWorkspaceJPanel
     */
    JPanel CardSequencePanel;
    Business business;

private java.util.ArrayList<PriceChangeRecord> priceChangeHistory = new java.util.ArrayList<>();

public MarketingWorkspaceJPanel(Business bz, JPanel jp) {
    this.business = bz;
    this.CardSequencePanel = jp;
    initComponents();
    
    // Initialize the Browse Products table
    refreshProductsTable();
    
    // Initialize the product combo box
    loadProductComboBox();
    
    // 🆕 Initialize supplier filter combo box
    loadSupplierFilterComboBox();
    
    updateDashboard();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSearchProduct = new javax.swing.JTextField();
        lblSupplierFilter = new javax.swing.JLabel();
        supplierFilterComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        productComboBox = new javax.swing.JComboBox<>();
        lblCurrentTarget = new javax.swing.JLabel();
        txtCurrentTarget = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNewTarget = new javax.swing.JTextField();
        btnIncrease10 = new javax.swing.JButton();
        btnDecrease10 = new javax.swing.JButton();
        btnApplyChanges = new javax.swing.JButton();
        btnAutoOptimize = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnRunSimulation = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSimulationResults = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        btnGenerateReport = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFinalReport = new javax.swing.JTextArea();
        dashboardPanel = new javax.swing.JPanel();
        lblTotalRevenue = new javax.swing.JLabel();
        lblProductCount = new javax.swing.JLabel();
        lblPerformanceSplit = new javax.swing.JLabel();
        lblBestProduct = new javax.swing.JLabel();
        btnUpdateDashboard = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Marketing Manager - Product Price Performance");

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Supplier Name", "Product Name", "Target Price", "Sales Above Target", "Sales Below Target"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productsTable);

        btnRefresh.setText("Refresh Data");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel5.setText("Search Product:");

        txtSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchProductActionPerformed(evt);
            }
        });

        lblSupplierFilter.setText("Filter by Supplier:");

        supplierFilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        supplierFilterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierFilterComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(lblSupplierFilter)
                        .addGap(18, 18, 18)
                        .addComponent(supplierFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplierFilter)
                    .addComponent(supplierFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Browse Products", jPanel1);

        jLabel2.setText("Select Product to Adjust:");

        productComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });

        lblCurrentTarget.setText("Current Target Price:");

        txtCurrentTarget.setEditable(false);

        jLabel3.setText("New Target Price:");

        btnIncrease10.setText("Increase by 10%");
        btnIncrease10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncrease10ActionPerformed(evt);
            }
        });

        btnDecrease10.setText("Decrease by 10%");
        btnDecrease10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecrease10ActionPerformed(evt);
            }
        });

        btnApplyChanges.setText("Apply Changes");
        btnApplyChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyChangesActionPerformed(evt);
            }
        });

        btnAutoOptimize.setBackground(new java.awt.Color(255, 102, 102));
        btnAutoOptimize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAutoOptimize.setForeground(new java.awt.Color(255, 255, 255));
        btnAutoOptimize.setText("⚡ Auto-Optimize ALL Prices (Smart Adjustment)");
        btnAutoOptimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoOptimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAutoOptimize)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblCurrentTarget)
                            .addComponent(jLabel3)
                            .addComponent(btnIncrease10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDecrease10)
                                .addGap(30, 30, 30)
                                .addComponent(btnApplyChanges))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCurrentTarget)
                                .addComponent(txtNewTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentTarget)
                    .addComponent(txtCurrentTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncrease10)
                    .addComponent(btnDecrease10)
                    .addComponent(btnApplyChanges))
                .addGap(18, 18, 18)
                .addComponent(btnAutoOptimize)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Adjust Prices", jPanel2);

        jLabel4.setText("Click below to calculate new revenue with adjusted prices");

        btnRunSimulation.setText("RUN SIMULATION");
        btnRunSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunSimulationActionPerformed(evt);
            }
        });

        txtSimulationResults.setEditable(false);
        txtSimulationResults.setColumns(20);
        txtSimulationResults.setRows(20);
        jScrollPane2.setViewportView(txtSimulationResults);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addGap(66, 66, 66)
                        .addComponent(btnRunSimulation)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRunSimulation)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Run Simulation", jPanel3);

        btnGenerateReport.setText("Generate Final Report");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        txtFinalReport.setColumns(90);
        txtFinalReport.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtFinalReport.setRows(25);
        jScrollPane3.setViewportView(txtFinalReport);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnGenerateReport))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnGenerateReport)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Final Report", jPanel4);

        dashboardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblTotalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalRevenue.setText("Total Revenue: $0");

        lblProductCount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductCount.setText("Products Analyzed: 0");

        lblPerformanceSplit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPerformanceSplit.setText("Above Target: 0 | Below Target: 0");

        lblBestProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBestProduct.setForeground(new java.awt.Color(0, 255, 51));
        lblBestProduct.setText("Best Performer: --");

        btnUpdateDashboard.setText("🔄 Update Dashboard");
        btnUpdateDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBestProduct)
                            .addComponent(lblPerformanceSplit)
                            .addComponent(lblProductCount)
                            .addComponent(lblTotalRevenue)))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnUpdateDashboard)))
                .addContainerGap(513, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTotalRevenue)
                .addGap(18, 18, 18)
                .addComponent(lblProductCount)
                .addGap(18, 18, 18)
                .addComponent(lblPerformanceSplit)
                .addGap(27, 27, 27)
                .addComponent(lblBestProduct)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateDashboard)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Dashboard", dashboardPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        System.out.println("🔄 Refreshing products table...");
        refreshProductsTable();
        javax.swing.JOptionPane.showMessageDialog(this, "Products table refreshed!");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnApplyChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyChangesActionPerformed
        // TODO add your handling code here:
        try {
        String selectedProductName = (String) productComboBox.getSelectedItem();
        if (selectedProductName == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a product first!");
            return;
        }
        
        int newTargetPrice = Integer.parseInt(txtNewTarget.getText());
        TheBusiness.ProductManagement.Product product = findProductByName(selectedProductName);
        
        if (product != null) {
            int oldPrice = product.getTargetPrice();
            
            // 🆕 Record the change BEFORE updating
            String changeType = newTargetPrice > oldPrice ? "INCREASE" : "DECREASE";
            priceChangeHistory.add(new PriceChangeRecord(
                selectedProductName, 
                oldPrice, 
                newTargetPrice, 
                changeType
            ));
            
            // Update the product
            product.updateProduct(
                product.getFloorPrice(),
                product.getCeilingPrice(),
                newTargetPrice
            );
            
            System.out.println("✅ Recorded price change: " + selectedProductName + 
                             " (" + oldPrice + " → " + newTargetPrice + ")");
            
            refreshProductsTable();
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "✅ Target price updated!\n" +
                "Product: " + selectedProductName + "\n" +
                "Old Target: $" + oldPrice + "\n" +
                "New Target: $" + newTargetPrice);
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid price!");
    }
    }//GEN-LAST:event_btnApplyChangesActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedProductName = (String) productComboBox.getSelectedItem();
        if (selectedProductName == null) return;
    
        // Find the product
        TheBusiness.ProductManagement.Product selectedProduct = findProductByName(selectedProductName);

        if (selectedProduct != null) {
            // Display current target price
            txtCurrentTarget.setText(String.valueOf(selectedProduct.getTargetPrice()));
            txtNewTarget.setText(String.valueOf(selectedProduct.getTargetPrice()));
        }
    }//GEN-LAST:event_productComboBoxActionPerformed

    private void btnIncrease10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncrease10ActionPerformed
        // TODO add your handling code here:
        try {
        int currentPrice = Integer.parseInt(txtCurrentTarget.getText());
        int newPrice = (int)(currentPrice * 1.10); // Increase by 10%
        txtNewTarget.setText(String.valueOf(newPrice));
        System.out.println("💰 Increased price from " + currentPrice + " to " + newPrice);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a product first!");
        }
    }//GEN-LAST:event_btnIncrease10ActionPerformed

    private void btnDecrease10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecrease10ActionPerformed
        // TODO add your handling code here:
        try {
        int currentPrice = Integer.parseInt(txtCurrentTarget.getText());
        int newPrice = (int)(currentPrice * 0.90); // Decrease by 10%
        txtNewTarget.setText(String.valueOf(newPrice));
        System.out.println("💰 Decreased price from " + currentPrice + " to " + newPrice);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a product first!");
        }
    }//GEN-LAST:event_btnDecrease10ActionPerformed

    private void btnRunSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunSimulationActionPerformed
        // TODO add your handling code here:
        System.out.println("🎮 Running simulation...");
    
        txtSimulationResults.setText("RUNNING SIMULATION...\n\n");

        // Calculate current total revenue
        int totalRevenue = business.getMasterOrderList().getSalesVolume();

        // Calculate total target revenue (what we SHOULD make with current targets)
        int totalTargetRevenue = calculateTotalTargetRevenue();

        // Calculate performance
        int revenuePerformance = totalRevenue - totalTargetRevenue;
        double performancePercentage = ((double)revenuePerformance / totalTargetRevenue) * 100;

        // Count products above/below target
        int productsAboveTarget = 0;
        int productsBelowTarget = 0;

        java.util.ArrayList<TheBusiness.Supplier.Supplier> suppliers = business.getSupplierDirectory().getSuplierList();
        for (TheBusiness.Supplier.Supplier supplier : suppliers) {
            for (TheBusiness.ProductManagement.Product product : supplier.getProductCatalog().getProductList()) {
                int above = product.getNumberOfProductSalesAboveTarget();
                int below = product.getNumberOfProductSalesBelowTarget();

                if (above > below) productsAboveTarget++;
                else if (below > above) productsBelowTarget++;
            }
        }

        // Display results
        StringBuilder result = new StringBuilder();
        result.append("═══════════════════════════════════════════════\n");
        result.append("           SIMULATION RESULTS\n");
        result.append("═══════════════════════════════════════════════\n\n");

        result.append("💰 REVENUE ANALYSIS:\n");
        result.append("   Actual Revenue:        $").append(String.format("%,d", totalRevenue)).append("\n");
        result.append("   Target Revenue:        $").append(String.format("%,d", totalTargetRevenue)).append("\n");
        result.append("   Performance:           $").append(String.format("%,d", revenuePerformance));

        if (revenuePerformance > 0) {
            result.append(" ✅ ABOVE TARGET\n");
        } else {
            result.append(" ❌ BELOW TARGET\n");
        }

        result.append("   Performance %:         ").append(String.format("%.2f%%", performancePercentage)).append("\n\n");

        result.append("📊 PRODUCT PERFORMANCE:\n");
        result.append("   Products Above Target: ").append(productsAboveTarget).append("\n");
        result.append("   Products Below Target: ").append(productsBelowTarget).append("\n\n");

        result.append("💡 RECOMMENDATIONS:\n");
        if (productsBelowTarget > productsAboveTarget) {
            result.append("   ⚠️  Many products selling below target!\n");
            result.append("   → Consider DECREASING target prices for slow products\n");
            result.append("   → This will improve sales volume\n");
        } else if (productsAboveTarget > productsBelowTarget * 2) {
            result.append("   🚀 Many products selling above target!\n");
            result.append("   → Consider INCREASING target prices for hot products\n");
            result.append("   → This will maximize profit margins\n");
        } else {
            result.append("   ✅ Price targets are well balanced!\n");
            result.append("   → Continue monitoring performance\n");
        }

        result.append("\n═══════════════════════════════════════════════\n");

        txtSimulationResults.setText(result.toString());

        System.out.println("✅ Simulation complete!");
    }//GEN-LAST:event_btnRunSimulationActionPerformed

    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        // TODO add your handling code here:
        System.out.println("📄 Generating final report...");
    
        StringBuilder report = new StringBuilder();

        // ========================================================================
        // HEADER
        // ========================================================================
        report.append("\n");
        report.append("╔═══════════════════════════════════════════════════════════════════════════════╗\n");
        report.append("║              FINAL PRODUCT PERFORMANCE REPORT                                 ║\n");
        report.append("╚═══════════════════════════════════════════════════════════════════════════════╝\n");
        report.append("\n");
        report.append("Generated: ").append(new java.util.Date()).append("\n\n");

        // ========================================================================
        // SECTION 1: ACTUAL PRICE CHANGES APPLIED (BEFORE & AFTER)
        // ========================================================================
        if (!priceChangeHistory.isEmpty()) {
            report.append("╔═══════════════════════════════════════════════════════════════════════════════╗\n");
            report.append("║ ✏️  PRICE CHANGES APPLIED (BEFORE & AFTER ADJUSTMENTS)                        ║\n");
            report.append("╠═══════════════════════════════════════════════════════════════════════════════╣\n");
            report.append(String.format("║ %-40s | %12s | %12s | %10s ║\n", 
                "Product Name", "Before", "After", "Change"));
            report.append("╠═══════════════════════════════════════════════════════════════════════════════╣\n");

            // Show up to 30 changes
            int changeCount = 0;
            for (PriceChangeRecord change : priceChangeHistory) {
                String name = truncate(change.productName, 40);
                int difference = change.afterPrice - change.beforePrice;
                String changeStr = (difference > 0 ? "+" : "") + String.format("$%,d", difference);

                report.append(String.format("║ %-40s | $%,10d | $%,10d | %10s ║\n",
                    name,
                    change.beforePrice,
                    change.afterPrice,
                    changeStr));

                changeCount++;
                if (changeCount >= 30) {
                    int remaining = priceChangeHistory.size() - 30;
                    if (remaining > 0) {
                        report.append(String.format("║ ... and %d more price changes                                                 ║\n", remaining));
                    }
                    break;
                }
            }

            report.append("╚═══════════════════════════════════════════════════════════════════════════════╝\n\n");
        } else {
            report.append("╔═══════════════════════════════════════════════════════════════════════════════╗\n");
            report.append("║ ⚠️  NO PRICE CHANGES APPLIED YET                                              ║\n");
            report.append("║                                                                               ║\n");
            report.append("║ Use 'Auto-Optimize' or manually adjust prices to see before/after changes.   ║\n");
            report.append("╚═══════════════════════════════════════════════════════════════════════════════╝\n\n");
        }

        // ========================================================================
        // SECTION 2: COLLECT PRODUCT PERFORMANCE DATA
        // ========================================================================
        java.util.ArrayList<ProductPerformanceData> performanceList = new java.util.ArrayList<>();

        java.util.ArrayList<TheBusiness.Supplier.Supplier> suppliers = business.getSupplierDirectory().getSuplierList();
        for (TheBusiness.Supplier.Supplier supplier : suppliers) {
            for (TheBusiness.ProductManagement.Product product : supplier.getProductCatalog().getProductList()) {

                int salesAbove = product.getNumberOfProductSalesAboveTarget();
                int salesBelow = product.getNumberOfProductSalesBelowTarget();
                int totalSales = salesAbove + salesBelow;

                if (totalSales > 0) {
                    ProductPerformanceData data = new ProductPerformanceData();
                    data.productName = product.toString();
                    data.targetPrice = product.getTargetPrice();
                    data.salesAbove = salesAbove;
                    data.salesBelow = salesBelow;
                    data.revenue = product.getSalesVolume();
                    data.pricePerformance = product.getOrderPricePerformance();

                    performanceList.add(data);
                }
            }
        }

        // Sort by revenue (highest first)
        performanceList.sort((a, b) -> Integer.compare(b.revenue, a.revenue));

        // ========================================================================
        // SECTION 3: TOP 10 PERFORMING PRODUCTS (BY REVENUE)
        // ========================================================================
        report.append("╔═══════════════════════════════════════════════════════════════════════════════╗\n");
        report.append("║ 🏆 TOP 10 PERFORMING PRODUCTS (By Revenue)                                    ║\n");
        report.append("╠═══════════════════════════════════════════════════════════════════════════════╣\n");
        report.append(String.format("║ %-40s | %12s | %6s | %6s | %10s ║\n", 
            "Product Name", "Target Price", "Above", "Below", "Revenue"));
        report.append("╠═══════════════════════════════════════════════════════════════════════════════╣\n");

        for (int i = 0; i < Math.min(10, performanceList.size()); i++) {
            ProductPerformanceData data = performanceList.get(i);
            String name = truncate(data.productName, 40);

            report.append(String.format("║ %-40s | $%,10d | %6d | %6d | $%,8d ║\n", 
                name, data.targetPrice, data.salesAbove, data.salesBelow, data.revenue));
        }
        report.append("╚═══════════════════════════════════════════════════════════════════════════════╝\n\n");

        // ========================================================================
        // SECTION 4: PRODUCTS NEEDING PRICE DECREASE (Selling Below Target)
        // ========================================================================
        report.append("╔═══════════════════════════════════════════════════════════════════════════════╗\n");
        report.append("║ ⚠️  PRODUCTS NEEDING PRICE DECREASE (Selling Below Target)                    ║\n");
        report.append("╠═══════════════════════════════════════════════════════════════════════════════╣\n");
        report.append(String.format("║ %-40s | %12s | %12s | %12s ║\n", 
            "Product Name", "Current", "Suggested", "Status"));
        report.append("╠═══════════════════════════════════════════════════════════════════════════════╣\n");

        int decreaseCount = 0;
        for (ProductPerformanceData data : performanceList) {
            int totalSales = data.salesAbove + data.salesBelow;

            if (data.salesBelow > data.salesAbove && totalSales >= 2) {
                String name = truncate(data.productName, 40);
                int suggested = (int)(data.targetPrice * 0.9);

                // Check if this product was actually adjusted
                String status = "NOT APPLIED";
                for (PriceChangeRecord change : priceChangeHistory) {
                    if (change.productName.equals(data.productName) && "DECREASE".equals(change.changeType)) {
                        status = "✅ APPLIED";
                        break;
                    }
                }

                report.append(String.format("║ %-40s | $%,10d | $%,10d | %12s ║\n", 
                    name, data.targetPrice, suggested, status));

                decreaseCount++;
                if (decreaseCount >= 15) break;
            }
        }

        if (decreaseCount == 0) {
            report.append("║ ✅ No products need price decrease                                            ║\n");
        }
        report.append("╚═══════════════════════════════════════════════════════════════════════════════╝\n\n");

        // ========================================================================
        // SECTION 5: PRODUCTS NEEDING PRICE INCREASE (Selling Above Target)
        // ========================================================================
        report.append("╔═══════════════════════════════════════════════════════════════════════════════╗\n");
        report.append("║ 🚀 PRODUCTS NEEDING PRICE INCREASE (Selling Above Target)                     ║\n");
        report.append("╠═══════════════════════════════════════════════════════════════════════════════╣\n");
        report.append(String.format("║ %-40s | %12s | %12s | %12s ║\n", 
            "Product Name", "Current", "Suggested", "Status"));
        report.append("╠═══════════════════════════════════════════════════════════════════════════════╣\n");

        int increaseCount = 0;
        for (ProductPerformanceData data : performanceList) {
            int totalSales = data.salesAbove + data.salesBelow;

            if (data.salesAbove > data.salesBelow && totalSales >= 2) {
                String name = truncate(data.productName, 40);
                int suggested = (int)(data.targetPrice * 1.1);

                // Check if this product was actually adjusted
                String status = "NOT APPLIED";
                for (PriceChangeRecord change : priceChangeHistory) {
                    if (change.productName.equals(data.productName) && "INCREASE".equals(change.changeType)) {
                        status = "✅ APPLIED";
                        break;
                    }
                }

                report.append(String.format("║ %-40s | $%,10d | $%,10d | %12s ║\n", 
                    name, data.targetPrice, suggested, status));

                increaseCount++;
                if (increaseCount >= 15) break;
            }
        }

        if (increaseCount == 0) {
            report.append("║ ✅ No products need price increase                                            ║\n");
        }
        report.append("╚═══════════════════════════════════════════════════════════════════════════════╝\n\n");

        // ========================================================================
        // SECTION 6: SUMMARY STATISTICS
        // ========================================================================
        report.append("╔═══════════════════════════════════════════════════════════════════════════════╗\n");
        report.append("║ 📊 EXECUTIVE SUMMARY                                                          ║\n");
        report.append("╠═══════════════════════════════════════════════════════════════════════════════╣\n");

        // Calculate summary metrics
        int totalProducts = performanceList.size();
        int totalPriceChanges = priceChangeHistory.size();
        int pricesIncreased = 0;
        int pricesDecreased = 0;

        for (PriceChangeRecord change : priceChangeHistory) {
            if ("INCREASE".equals(change.changeType)) pricesIncreased++;
            else if ("DECREASE".equals(change.changeType)) pricesDecreased++;
        }

        int totalRevenue = business.getMasterOrderList().getSalesVolume();

        report.append(String.format("║ Total Products Analyzed:          %,10d                                  ║\n", totalProducts));
        report.append(String.format("║ Total Business Revenue:           $%,10d                                 ║\n", totalRevenue));
        report.append("║                                                                               ║\n");
        report.append(String.format("║ Price Adjustments Applied:        %,10d                                  ║\n", totalPriceChanges));
        report.append(String.format("║   - Prices Increased (+10%%):      %,10d                                  ║\n", pricesIncreased));
        report.append(String.format("║   - Prices Decreased (-10%%):      %,10d                                  ║\n", pricesDecreased));
        report.append("║                                                                               ║\n");
        report.append(String.format("║ Products Above Target:            %,10d                                  ║\n", increaseCount));
        report.append(String.format("║ Products Below Target:            %,10d                                  ║\n", decreaseCount));
        report.append("║                                                                               ║\n");

        // Calculate adjustment percentage
        double adjustmentRate = totalProducts > 0 ? (totalPriceChanges * 100.0 / totalProducts) : 0;
        report.append(String.format("║ Adjustment Rate:                  %5.1f%%                                    ║\n", adjustmentRate));

        report.append("╚═══════════════════════════════════════════════════════════════════════════════╝\n\n");

        // ========================================================================
        // SECTION 7: RECOMMENDATIONS
        // ========================================================================
        report.append("╔═══════════════════════════════════════════════════════════════════════════════╗\n");
        report.append("║ 💡 RECOMMENDATIONS                                                            ║\n");
        report.append("╠═══════════════════════════════════════════════════════════════════════════════╣\n");

        if (totalPriceChanges == 0) {
            report.append("║ ⚠️  No price adjustments have been applied yet.                               ║\n");
            report.append("║                                                                               ║\n");
            report.append("║ NEXT STEPS:                                                                   ║\n");
            report.append("║   1. Click 'Auto-Optimize' to automatically adjust all prices                ║\n");
            report.append("║   2. Or manually adjust individual product prices                            ║\n");
            report.append("║   3. Re-run this report to see before/after comparisons                      ║\n");
        } else {
            report.append(String.format("║ ✅ Successfully optimized %d product prices (%.1f%% of catalog)              ║\n", 
                totalPriceChanges, adjustmentRate));
            report.append("║                                                                               ║\n");

            if (decreaseCount > increaseCount * 2) {
                report.append("║ ⚠️  ALERT: Many products selling below target                                 ║\n");
                report.append("║   → Consider reviewing product positioning and market fit                    ║\n");
            } else if (increaseCount > decreaseCount * 2) {
                report.append("║ 🚀 OPPORTUNITY: Many products selling above target                            ║\n");
                report.append("║   → Strong market demand - prices have been optimized                        ║\n");
            } else {
                report.append("║ ✅ BALANCED: Price targets are well-calibrated with market demand            ║\n");
                report.append("║   → Continue monitoring and make incremental adjustments                     ║\n");
            }
        }

        report.append("╚═══════════════════════════════════════════════════════════════════════════════╝\n");

        // ========================================================================
        // DISPLAY THE REPORT
        // ========================================================================
        txtFinalReport.setFont(new java.awt.Font("Courier New", java.awt.Font.PLAIN, 11));
        txtFinalReport.setText(report.toString());

        System.out.println("✅ Final report generated successfully!");
        System.out.println("   📊 Products analyzed: " + totalProducts);
        System.out.println("   ✏️  Price changes applied: " + totalPriceChanges);
        System.out.println("   📈 Prices increased: " + pricesIncreased);
        System.out.println("   📉 Prices decreased: " + pricesDecreased);
    }

// Helper method to truncate long names
private String truncate(String text, int maxLength) {
    if (text.length() <= maxLength) {
        return text;
    }
    return text.substring(0, maxLength - 3) + "...";
}

// Helper class for sorting
private class ProductPerformanceData {
    String productName;
    int targetPrice;
    int salesAbove;
    int salesBelow;
    int revenue;
    int pricePerformance;
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    private void btnUpdateDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDashboardActionPerformed
        // TODO add your handling code here:
        updateDashboard();
    }//GEN-LAST:event_btnUpdateDashboardActionPerformed

    private void txtSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchProductActionPerformed
        // TODO add your handling code here:
        String searchText = txtSearchProduct.getText().toLowerCase();
    
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) productsTable.getModel();
    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = 
        new javax.swing.table.TableRowSorter<>(model);
    
    productsTable.setRowSorter(sorter);
    
    if (searchText.trim().length() == 0) {
        sorter.setRowFilter(null);
    } else {
        sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + searchText));
    }
    }//GEN-LAST:event_txtSearchProductActionPerformed

    private void btnAutoOptimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoOptimizeActionPerformed
        // TODO add your handling code here:
        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "This will automatically adjust ALL product prices based on performance.\n\n" +
        "Products selling ABOVE target → Price increases by 10%\n" +
        "Products selling BELOW target → Price decreases by 10%\n\n" +
        "This affects all 2,500 products. Continue?",
        "Auto-Optimize Confirmation",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.WARNING_MESSAGE);
    
    if (confirm != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }
    
    System.out.println("⚡ AUTO-OPTIMIZATION STARTED...");
    
    int increased = 0;
    int decreased = 0;
    int unchanged = 0;
    
    // 🆕 Clear previous auto-optimization history
    priceChangeHistory.clear();
    
    // Loop through ALL products
    java.util.ArrayList<TheBusiness.Supplier.Supplier> suppliers = business.getSupplierDirectory().getSuplierList();
    
    for (TheBusiness.Supplier.Supplier supplier : suppliers) {
        for (TheBusiness.ProductManagement.Product product : supplier.getProductCatalog().getProductList()) {
            
            int above = product.getNumberOfProductSalesAboveTarget();
            int below = product.getNumberOfProductSalesBelowTarget();
            int currentTarget = product.getTargetPrice();
            int totalSales = above + below;
            
            // CHANGED: Only require 2 total sales and a clear winner
            if (totalSales >= 2) {
                
                if (above > below) {
                    int newTarget = (int)(currentTarget * 1.10);
                    
                    // 🆕 Record the change
                    priceChangeHistory.add(new PriceChangeRecord(
                        product.toString(),
                        currentTarget,
                        newTarget,
                        "INCREASE"
                    ));
                    
                    product.updateProduct(product.getFloorPrice(), product.getCeilingPrice(), newTarget);
                    increased++;
                    
                } else if (below > above) {
                    int newTarget = (int)(currentTarget * 0.90);
                    
                    // 🆕 Record the change
                    priceChangeHistory.add(new PriceChangeRecord(
                        product.toString(),
                        currentTarget,
                        newTarget,
                        "DECREASE"
                    ));
                    
                    product.updateProduct(product.getFloorPrice(), product.getCeilingPrice(), newTarget);
                    decreased++;
                    
                } else {
                    unchanged++;
                }
            } else {
                unchanged++;
            }
        }
    }
    
    System.out.println("✅ Recorded " + priceChangeHistory.size() + " price changes");
    
    
    System.out.println("✅ AUTO-OPTIMIZATION COMPLETE!");
    System.out.println("   📈 Increased: " + increased + " products");
    System.out.println("   📉 Decreased: " + decreased + " products");
    System.out.println("   ➡️  Unchanged: " + unchanged + " products");
    
    // Refresh everything
    refreshProductsTable();
    loadProductComboBox();
    
    // Show results
    javax.swing.JOptionPane.showMessageDialog(this,
        String.format("⚡ AUTO-OPTIMIZATION COMPLETE!\n\n" +
                     "📈 Increased: %d products (+10%%)\n" +
                     "📉 Decreased: %d products (-10%%)\n" +
                     "➡️  Unchanged: %d products\n\n" +
                     "All tables have been updated!",
                     increased, decreased, unchanged),
        "Optimization Results",
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAutoOptimizeActionPerformed

    private void supplierFilterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierFilterComboBoxActionPerformed
        // TODO add your handling code here:
        // Get selected supplier
    String selectedSupplier = (String) supplierFilterComboBox.getSelectedItem();
    
    if (selectedSupplier == null) {
        return; // No selection
    }
    
    System.out.println("🔽 Supplier filter changed to: " + selectedSupplier);
    
    // Check if "All Suppliers" is selected
    if ("All Suppliers".equals(selectedSupplier)) {
        // Show all products
        refreshProductsTable();
    } else {
        // Show only products from selected supplier
        refreshProductsTableForSupplier(selectedSupplier);
    }
    
    // Update status
    updateFilterStatus(selectedSupplier);
    }//GEN-LAST:event_supplierFilterComboBoxActionPerformed

    /**
 * Updates the UI to show filter status
 * @param supplierName Currently selected supplier
 */
private void updateFilterStatus(String supplierName) {
    int rowCount = productsTable.getRowCount();
    
    if ("All Suppliers".equals(supplierName)) {
        System.out.println("📊 Showing all " + rowCount + " products");
    } else {
        System.out.println("📊 Showing " + rowCount + " products from " + supplierName);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyChanges;
    private javax.swing.JButton btnAutoOptimize;
    private javax.swing.JButton btnDecrease10;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnIncrease10;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRunSimulation;
    private javax.swing.JButton btnUpdateDashboard;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBestProduct;
    private javax.swing.JLabel lblCurrentTarget;
    private javax.swing.JLabel lblPerformanceSplit;
    private javax.swing.JLabel lblProductCount;
    private javax.swing.JLabel lblSupplierFilter;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JComboBox<String> productComboBox;
    private javax.swing.JTable productsTable;
    private javax.swing.JComboBox<String> supplierFilterComboBox;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtCurrentTarget;
    private javax.swing.JTextArea txtFinalReport;
    private javax.swing.JTextField txtNewTarget;
    private javax.swing.JTextField txtSearchProduct;
    private javax.swing.JTextArea txtSimulationResults;
    // End of variables declaration//GEN-END:variables

private void refreshProductsTable() {
    // Clear existing rows
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) productsTable.getModel();
    model.setRowCount(0);
    
    // Get all suppliers
    java.util.ArrayList<TheBusiness.Supplier.Supplier> suppliers = business.getSupplierDirectory().getSuplierList();
    
    System.out.println("📊 Loading products into table...");
    int productCount = 0;
    
    // Loop through all suppliers and their products
    for (TheBusiness.Supplier.Supplier supplier : suppliers) {
        TheBusiness.ProductManagement.ProductCatalog catalog = supplier.getProductCatalog();
        
        for (TheBusiness.ProductManagement.Product product : catalog.getProductList()) {
            // Calculate performance metrics
            int numAboveTarget = product.getNumberOfProductSalesAboveTarget();
            int numBelowTarget = product.getNumberOfProductSalesBelowTarget();
            
            // Add row to table - NOW WITH SUPPLIER NAME
            Object[] row = {
                supplier.getName(),      // 🆕 ADDED: Supplier Name (Column 0)
                product.toString(),      // Product Name (Column 1)
                product.getTargetPrice(), // Target Price (Column 2)
                numAboveTarget,          // Sales Above Target (Column 3)
                numBelowTarget           // Sales Below Target (Column 4)
            };
            
            model.addRow(row);
            productCount++;
        }
    }
    
    // Apply color coding
    colorCodeTableRows();
    
    System.out.println("✅ Loaded " + productCount + " products into table with color coding and supplier names");
}

// NEW METHOD: Color code rows based on performance
private void colorCodeTableRows() {
    productsTable.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value, boolean isSelected, 
                boolean hasFocus, int row, int column) {
            
            java.awt.Component cell = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);
            
            if (!isSelected) {
                
                if (column == 0) {
        cell.setBackground(new java.awt.Color(245, 245, 245)); // Very light gray
        cell.setFont(cell.getFont().deriveFont(java.awt.Font.BOLD)); // Make supplier names bold
        return cell;
    }
                // 🆕 UPDATED: Column indices shifted by 1 because we added Supplier column
                int above = (Integer) table.getValueAt(row, 3); // Column 3 = Above Target (was 2)
                int below = (Integer) table.getValueAt(row, 4); // Column 4 = Below Target (was 3)
                
                if (above > below && above > 0) {
                    cell.setBackground(new java.awt.Color(200, 255, 200)); // Light green
                } else if (below > above && below > 0) {
                    cell.setBackground(new java.awt.Color(255, 200, 200)); // Light red
                } else if (above == 0 && below == 0) {
                    cell.setBackground(new java.awt.Color(240, 240, 240)); // Light gray
                } else {
                    cell.setBackground(java.awt.Color.WHITE);
                }
            }
            
            return cell;
        }
    });
}

private void updateDashboard() {
    System.out.println("📊 Updating dashboard...");
    
    // Calculate metrics
    int totalRevenue = business.getMasterOrderList().getSalesVolume();
    
    int productsAbove = 0;
    int productsBelow = 0;
    int productCount = 0;
    
    String bestProductName = "";
    int bestProductRevenue = 0;
    
    // Loop through all products
    java.util.ArrayList<TheBusiness.Supplier.Supplier> suppliers = business.getSupplierDirectory().getSuplierList();
    for (TheBusiness.Supplier.Supplier supplier : suppliers) {
        for (TheBusiness.ProductManagement.Product product : supplier.getProductCatalog().getProductList()) {
            productCount++;
            
            int above = product.getNumberOfProductSalesAboveTarget();
            int below = product.getNumberOfProductSalesBelowTarget();
            
            if (above > below) productsAbove++;
            else if (below > above) productsBelow++;
            
            // Track best product
            int revenue = product.getSalesVolume();
            if (revenue > bestProductRevenue) {
                bestProductRevenue = revenue;
                bestProductName = product.toString();
            }
        }
    }
    
    // Update labels
    lblTotalRevenue.setText(String.format("💰 Total Revenue: $%,d", totalRevenue));
    lblProductCount.setText(String.format("📦 Products Analyzed: %,d", productCount));
    lblPerformanceSplit.setText(String.format("✅ Above Target: %d | ⚠️ Below Target: %d", productsAbove, productsBelow));
    lblBestProduct.setText(String.format("🏆 Best Performer: %s ($%,d)", 
        bestProductName.length() > 30 ? bestProductName.substring(0, 30) + "..." : bestProductName, 
        bestProductRevenue));
    
    System.out.println("✅ Dashboard updated!");
}

private void loadProductComboBox() {
    productComboBox.removeAllItems();
    
    // Get all products
    java.util.ArrayList<TheBusiness.Supplier.Supplier> suppliers = business.getSupplierDirectory().getSuplierList();
    
    for (TheBusiness.Supplier.Supplier supplier : suppliers) {
        TheBusiness.ProductManagement.ProductCatalog catalog = supplier.getProductCatalog();
        
        for (TheBusiness.ProductManagement.Product product : catalog.getProductList()) {
            productComboBox.addItem(product.toString());
        }
    }
    
    System.out.println("✅ Loaded products into combo box");
}


private void loadSupplierFilterComboBox() {
    System.out.println("🔄 Loading supplier filter...");
    
    // Clear existing items
    supplierFilterComboBox.removeAllItems();
    
    // Add "All Suppliers" as default option
    supplierFilterComboBox.addItem("All Suppliers");
    
    // Get all suppliers from business
    java.util.ArrayList<TheBusiness.Supplier.Supplier> suppliers = 
        business.getSupplierDirectory().getSuplierList();
    
    // Add each supplier name
    for (TheBusiness.Supplier.Supplier supplier : suppliers) {
        supplierFilterComboBox.addItem(supplier.getName());
    }
    
    System.out.println("✅ Loaded " + suppliers.size() + " suppliers into filter");
}

/**
 * Refreshes the products table showing only products from selected supplier
 * @param supplierName The name of the supplier to filter by
 */
private void refreshProductsTableForSupplier(String supplierName) {
    System.out.println("🔍 Filtering products for supplier: " + supplierName);
    
    // Clear existing rows
    javax.swing.table.DefaultTableModel model = 
        (javax.swing.table.DefaultTableModel) productsTable.getModel();
    model.setRowCount(0);
    
    // Get all suppliers
    java.util.ArrayList<TheBusiness.Supplier.Supplier> suppliers = 
        business.getSupplierDirectory().getSuplierList();
    
    int productCount = 0;
    
    // Loop through suppliers
    for (TheBusiness.Supplier.Supplier supplier : suppliers) {
        
        // Check if this is the supplier we want to filter by
        if (!supplier.getName().equals(supplierName)) {
            continue; // Skip this supplier
        }
        
        // Get this supplier's products
        TheBusiness.ProductManagement.ProductCatalog catalog = supplier.getProductCatalog();
        
        for (TheBusiness.ProductManagement.Product product : catalog.getProductList()) {
            // Calculate performance metrics
            int numAboveTarget = product.getNumberOfProductSalesAboveTarget();
            int numBelowTarget = product.getNumberOfProductSalesBelowTarget();
            
            // Add row to table
            Object[] row = {
                supplier.getName(),
                product.toString(),
                product.getTargetPrice(),
                numAboveTarget,
                numBelowTarget
            };
            
            model.addRow(row);
            productCount++;
        }
        
        break; // We found the supplier, no need to continue
    }
    
    // Apply color coding
    colorCodeTableRows();
    
    System.out.println("✅ Loaded " + productCount + " products from " + supplierName);
}

// Helper method to find product by name
private TheBusiness.ProductManagement.Product findProductByName(String name) {
    java.util.ArrayList<TheBusiness.Supplier.Supplier> suppliers = business.getSupplierDirectory().getSuplierList();
    
    for (TheBusiness.Supplier.Supplier supplier : suppliers) {
        for (TheBusiness.ProductManagement.Product product : supplier.getProductCatalog().getProductList()) {
            if (product.toString().equals(name)) {
                return product;
            }
        }
    }
    
    return null;
}

// Calculate what total revenue SHOULD be with current target prices
private int calculateTotalTargetRevenue() {
    int total = 0;
    
    TheBusiness.OrderManagement.MasterOrderList orderList = business.getMasterOrderList();
    // We need to iterate through all orders and sum up target prices
    // This is an estimate based on actual quantities sold
    
    java.util.ArrayList<TheBusiness.Supplier.Supplier> suppliers = business.getSupplierDirectory().getSuplierList();
    
    for (TheBusiness.Supplier.Supplier supplier : suppliers) {
        for (TheBusiness.ProductManagement.Product product : supplier.getProductCatalog().getProductList()) {
            // Get how many times this product was sold (above + below target)
            int timesSold = product.getNumberOfProductSalesAboveTarget() + 
                           product.getNumberOfProductSalesBelowTarget();
            
            // Multiply by target price (this is what we WANTED to make)
            total += product.getTargetPrice() * timesSold;
        }
    }
    
    return total;
}



/**
 * Helper class to track price changes
 */
private class PriceChangeRecord {
    String productName;
    int beforePrice;
    int afterPrice;
    String changeType; // "INCREASE" or "DECREASE"
    java.util.Date timestamp;
    
    public PriceChangeRecord(String name, int before, int after, String type) {
        this.productName = name;
        this.beforePrice = before;
        this.afterPrice = after;
        this.changeType = type;
        this.timestamp = new java.util.Date();
    }
}

}
